### PR TITLE
Update rules.html

### PR DESCRIPTION
**Pull request by dependants**
Edited rules.html, making a few additions, editing current guidelines.

### CODE REVIEW

**Comment by jellz** [comment]
ok, a few things;
- we can see what files you change, no need to tell us
- not required, but your title should be 'Add rules' or 'Edit the rules'
- you used **professionalization** incorrectly

**Comment by jellz** [comment]
congrats on your first pr tho :+1:

**Comment by dependants** [comment]
I try to make things sound more professional, that's why I threw in 'Professionalization' because I thought it fit in. 

I'll make sure to make the title something like the options you suggested above, thank you for the feedback.

**Comment by jellz** [comment]
all good!

**Comment by jellz** [comment]
Closed due to v2 rewrite

**Pull request closed without merging**
